tdevPath: ../../gbsl-informatik/teaching-dev
expectedTdevBranch: main
trackedElements:
    - src: docusaurus.config.ts
      dst: docusaurus.config.ts
    - src: tsconfig.package.json
      dst: tsconfig.package.json
    - src: src/
      dst: src
      ignore:
          - pages/index.tsx
          - pages/__index.tsx
          - pages/.gitignore
          - theme/**
          - components/documents/CodeEditor/Editor/Result/Graphics/Turtle.tsx
          - components/documents/CodeEditor/Editor/utils/saveSvg.ts
          - components/documents/CodeEditor/utils/tests/plugin.test.ts
          - components/documents/CodeEditor/utils/svg2grbl.ts
    - src: src/theme/Root.tsx
      dst: src/theme/Root.tsx
    - src: src/theme/EditThisPage/
      dst: src/theme/EditThisPage/
    - src: src/theme/DocSidebarItem/
      dst: src/theme/DocSidebarItem/
    - src: src/theme/Admonition/
      dst: src/theme/Admonition/
    - src: src/theme/CodeBlock/
      dst: src/theme/CodeBlock/
    - src: packages/tdev/
      dst: packages/tdev
    - src: updateSync/
      dst: updateSync
    - src: .prettierrc
      dst: .prettierrc
    - src: vitest.config.ts
      dst: vitest.config.ts
    - src: static/tdev-artifacts/
      dst: static/tdev-artifacts/
      ignore:
          - '*/**'
watchedElements:
    - .babel.config.js
    - package.json
    - .env.example
    - static/bry-libs/
    - tsconfig.tdev.json
    - src/theme/
